import os
import requests
import json
from dotenv import load_dotenv

load_dotenv()

PINATA_API_KEY = os.getenv("PINATA_API_KEY")
PINATA_SECRET_API_KEY = os.getenv("PINATA_SECRET_API_KEY")

def upload_to_pinata(image_bytes: bytes, filename: str) -> str:
    url = "https://api.pinata.cloud/pinning/pinFileToIPFS"
    headers = {
        "pinata_api_key": PINATA_API_KEY,
        "pinata_secret_api_key": PINATA_SECRET_API_KEY,
    }
    files = {
        "file": (filename, image_bytes),
    }

    try:
        response = requests.post(url, headers=headers, files=files)
        response.raise_for_status()
        ipfs_hash = response.json()["IpfsHash"]
        print(f"✅ Uploaded to IPFS: {ipfs_hash}")
        return f"https://gateway.pinata.cloud/ipfs/{ipfs_hash}"
    except requests.exceptions.RequestException as e:
        print(f"❌ Upload to Pinata failed: {e}")
        raise


def upload_metadata_to_pinata(name: str, description: str, image_url: str) -> str:
    url = "https://api.pinata.cloud/pinning/pinJSONToIPFS"
    headers = {
        "Content-Type": "application/json",
        "pinata_api_key": PINATA_API_KEY,
        "pinata_secret_api_key": PINATA_SECRET_API_KEY,
    }

    metadata = {
        "name": name,
        "description": description,
        "image": image_url,
        "attributes": [
            {
                "trait_type": "Generated by",
                "value": "Stable Diffusion XL"
            }
        ]
    }

    try:
        response = requests.post(url, headers=headers, data=json.dumps(metadata))
        response.raise_for_status()
        ipfs_hash = response.json()["IpfsHash"]
        print(f"✅ Metadata uploaded: {ipfs_hash}")
        return f"https://gateway.pinata.cloud/ipfs/{ipfs_hash}"
    except requests.exceptions.RequestException as e:
        print(f"❌ Upload metadata to Pinata failed: {e}")
        raise
